// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSP1XCJxgFSoNPjwwmgnoRteBgPOn3WZw',
    appId: '1:242901186197:web:cd07fa681642898d178d9c',
    messagingSenderId: '242901186197',
    projectId: 'sample-firebase-ai-app-c7883',
    authDomain: 'sample-firebase-ai-app-c7883.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-c7883.firebasestorage.app',
    measurementId: 'G-R82VKQSZMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_kprcjzhYn1wVDFrAbjkTPTa-k2TI_Jk',
    appId: '1:242901186197:android:d3e543b5d7c2d33b178d9c',
    messagingSenderId: '242901186197',
    projectId: 'sample-firebase-ai-app-c7883',
    storageBucket: 'sample-firebase-ai-app-c7883.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF9ssCxiJ8QYG0nKDQvUTIxOzXvgzzRis',
    appId: '1:242901186197:ios:8064e891b7c296e6178d9c',
    messagingSenderId: '242901186197',
    projectId: 'sample-firebase-ai-app-c7883',
    storageBucket: 'sample-firebase-ai-app-c7883.firebasestorage.app',
    iosClientId: '242901186197-k0kflho05ctojg9da4vuvf88fe7c6d1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.orionAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF9ssCxiJ8QYG0nKDQvUTIxOzXvgzzRis',
    appId: '1:242901186197:ios:8064e891b7c296e6178d9c',
    messagingSenderId: '242901186197',
    projectId: 'sample-firebase-ai-app-c7883',
    storageBucket: 'sample-firebase-ai-app-c7883.firebasestorage.app',
    iosClientId: '242901186197-k0kflho05ctojg9da4vuvf88fe7c6d1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.orionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSP1XCJxgFSoNPjwwmgnoRteBgPOn3WZw',
    appId: '1:242901186197:web:1b13a89469b1f148178d9c',
    messagingSenderId: '242901186197',
    projectId: 'sample-firebase-ai-app-c7883',
    authDomain: 'sample-firebase-ai-app-c7883.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-c7883.firebasestorage.app',
    measurementId: 'G-GDPBK215H8',
  );
}
