// lib/main.dart

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
// Import your AuthProvider
import 'src/auth/auth_provider.dart'; // Adjust path as needed
// Import your RootNavigator or initial app widget
// import 'package:orion_app/src/navigation/root_navigator.dart'; // Example

// Import Firebase options (generated by FlutterFire CLI)
import 'firebase_options.dart'; // Ensure this file exists and is configured

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const OrionApp());
}

class OrionApp extends StatelessWidget {
  const OrionApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Provide AuthProvider at the top of your widget tree
    return ChangeNotifierProvider<AuthProvider>(
      create: (_) => AuthProvider(),
      child: MaterialApp(
        title: 'Orion Calendar Assistant',
        theme: ThemeData(
          primarySwatch: Colors.blue,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        // Your RootNavigator will consume AuthProvider to decide
        // whether to show LoginScreen or MainApp screens.
        // home: RootNavigator(), // Example
        home: const AuthGate(), // Placeholder for navigation logic
      ),
    );
  }
}

// Placeholder widget to demonstrate consuming AuthProvider
// This logic will typically be in your RootNavigator (FE-TASK-7)
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    // Listen to AuthProvider
    final authProvider = Provider.of<AuthProvider>(context);

    if (authProvider.isLoading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }

    if (authProvider.isAuthenticated) {
      // Replace with your main app screen/navigator
      return Scaffold(
        appBar: AppBar(title: const Text('Orion Main App')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Welcome, ${authProvider.currentUser?.displayName ?? authProvider.currentUser?.email ?? 'User'}!'),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () => authProvider.signOut(),
                child: const Text('Sign Out'),
              ),
            ],
          ),
        ),
      );
    } else {
      // Replace with your LoginScreen (FE-TASK-6)
      // For now, just a button to trigger login
      return Scaffold(
        appBar: AppBar(title: const Text('Orion Login')),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (authProvider.errorMessage != null)
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(authProvider.errorMessage!, style: const TextStyle(color: Colors.red)),
                ),
              ElevatedButton(
                onPressed: () => authProvider.signInWithGoogle(),
                child: const Text('Sign in with Google'),
              ),
            ],
          ),
        ),
      );
    }
  }
}
